### ISSUE TITLE
Game crash on non-vanilla Achievement event [Cause unknown, inter-mod interaction]

### ISSUE THREAD

**Issue by SilearFlare** [FalsePattern/SuperSoundMuffler-Legacy#2]
Hello Again!
I was testing the mod in my modpack and started a new world. Picked up a rock, got an achievement, game crashed. Restarted the world, picked up a flower (which triggered another achievement) and the game crashed again. It did not happen with Vanilla achievements.
https://pastebin.com/iYuuT0sC
The error seems generic, so I can't really pinpoint it anywhere. Testing it in a more compact environment (Botania+Qwertech [which adds a sound when an achievement is gained] + SSM-L) did not crash the game unfortunately, so my initial hunch wasn't correct.

**Comment by makamys** [comment]
Adding any other audio mods you had (e.g. MAtmos, Sound Filters) to the test instance might help reproduce it.

**Comment by FalsePattern** [comment]
I made a temporary workaround for this bug until the true cause is found, it might lead to some temporary audio bugs when the crash is suppressed.
The sources are available in the [weird-crash-workaround](https://github.com/FalsePattern/SuperSoundMuffler-Legacy/tree/weird-crash-workaround) branch, and a usable jar is available [here](https://github.com/FalsePattern/SuperSoundMuffler-Legacy/releases/tag/1.1.2-alpha0001%2Buglyworkaround), or on the curseforge page as an alpha release.
I am going to be busy for a couple weeks, i will look into this issue more after i return.

**Comment by SilearFlare** [comment]
Update:
I did try testing with all the sound mods installed and still couldn't reproduce it. On top of that, I seem to have recently managed to get the crash without the mod for the first time, after a couple hours of playing (again on an achievement) so I think it's safe to close this.
Thanks for your time as always, and feel free to reopen this in the future in case something else comes up.
